INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Crime and Punishment','Fyodor Dostoyevski','975','Russian',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('The Da Vinci Code','Dan Brown','660','English',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Origin','Dan Brown','463','English',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Cyber Storm','Matthew Mather','358','English',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('The Power of Positive Energy','Andrian Teodoro','125','English',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Lord Of The Rings','Tolkien','1200','English',0);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('new book','new author','65656','English',0);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Please enter a book name','Please enter a author name','Please enter page size','Please enter a Language',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Please enter a book name','Please enter a author name','Please enter page size','Please enter a Language',0);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('adsfasdf','Please enter a author name','Please enter page size','Please enter a Language',0);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('new book','Please enter a author name','Please enter page size','Please enter a Language',1);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Please enter a book name','Please enter a author name','Please enter page size','Please enter a Language',0);
INSERT INTO books (book_name,book_author,book_page,book_language,book_status) VALUES ('Please enter a book name','Please enter a author name','Please enter page size','Please enter a Language',0);
INSERT INTO members (member_name,member_phone) VALUES ('David','+787851515');
INSERT INTO members (member_name,member_phone) VALUES ('Kate','+1215445');
INSERT INTO members (member_name,member_phone) VALUES ('new member','+1215454');
INSERT INTO members (member_name,member_phone) VALUES ('Please enter a book name','Please enter Phone Number');
INSERT INTO borrows (bbook_id,bmember_id) VALUES ('1-Crime and Punishment','1-David');
INSERT INTO borrows (bbook_id,bmember_id) VALUES ('3-Origin','3-new member');
INSERT INTO borrows (bbook_id,bmember_id) VALUES ('11-new book','2-Kate');
INSERT INTO borrows (bbook_id,bmember_id) VALUES ('8-Please enter a book name','2-Kate');
INSERT INTO borrows (bbook_id,bmember_id) VALUES ('4-Cyber Storm','2-Kate');
INSERT INTO borrows (bbook_id,bmember_id) VALUES ('2-The Da Vinci Code','2-Kate');